realty/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, url

urlpatterns = patterns('realty.views',
    url(r'^$', 'index', name='realty_index'),
    url(r'^page_(?P<page_id>\d+)/$', 'index', name='realty_index_page'),
    url(r'^cat_(?P<id>\d+)/$', 'category', name='realty_category'),
    url(r'^cat_(?P<id>\d+)/num_(?P<page_id>\d+)/$', 'category', name='realty_category'),
    url(r'^reg_(?P<id>\d+)/$', 'country', name='realty_country'),
    url(r'^reg_(?P<id>\d+)/num_(?P<page_id>\d+)/$', 'country', name='realty_country'),
    url(r'^cat_(?P<cat_id>\d+)/(?P<item_id>\d+)/', 'item', name='realty_item'),
    url(r'^order_form/$', 'order_form', name='realty_order_form'),
)

urls.py
#-*- coding:utf-8 -*-
from django.conf.urls import patterns, include, url
from django.conf.urls.i18n import i18n_patterns

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = patterns('',
    # Examples:
    url(r'^$', 'cms.views.index', name='index'),
    url(r'^test_index/$', 'cms.views.test_index', name='test_index'),


    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^tinymce/', include('tinymce.urls')),

    url(r'^pages/(?P<pageid>\d+)/$', 'cms.views.pages', name='pages'),
    url(r'^pages/(?P<pageurl>\w+)/$', 'cms.views.pages', name='pages'),

    url(r'^(?P<sect_path>\w+)/news/$', 'cms.views.news', name='news'),
    url(r'^(?P<sect_path>\w+)/news/num_(?P<page_id>\d+)/$', 'cms.views.news', name='news_page'),
    url(r'^(?P<sect_path>\w+)/news/(?P<id>\d+)/$', 'cms.views.news_one', name='news_one'),

    url(r'^voting_add/$', 'cms.views.voting_add', name='voting_add'),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),

    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.MEDIA_ROOT}),
    url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.STATIC_ROOT}),

    url(r'^robots.txt$', 'cms.views.robotstxt', name='robotstxt'),
    url(r'^js_lang.js$', 'cms.views.js_lang', name='js_lang'),


)

# Пользователи
urlpatterns += patterns('',
    url(r'^user/', include('person.urls')),
)

# Туры
urlpatterns += patterns('',
    url(r'^tours/', include('tours.urls')),
)

# Недвижимость
urlpatterns += patterns('',
    url(r'^nedvizhimost/', include('realty.urls')),
)

# Отели
urlpatterns += patterns('',
    url(r'^hotels/', include('hotels.urls')),
)

# SEO
urlpatterns += patterns('',
    url(r'^seo/', include('seo.urls')),
)

# Обратная связь
urlpatterns += patterns('',
    url(r'^(\w+)/feedback/', include('feedback.urls')),
)



# разделы
urlpatterns += patterns('',
    url(r'^(\w+)/(?P<suburl>\w+)/$', 'cms.views.subsection', name='sub_section'),
    url(r'^(?P<url>\w+)/$', 'cms.views.section', name='mega_section'),

)

if settings.DEBUG:
    if settings.MEDIA_ROOT:
        urlpatterns += static(settings.MEDIA_URL,
            document_root=settings.MEDIA_ROOT)
    # Эта строка опциональна и будет добавлять url'ы только при DEBUG = True
    urlpatterns += staticfiles_urlpatterns()

realty/models.py
#-*- coding:utf-8 -*-
from django.utils.translation import ugettext_lazy as _
from django.db import models
from tinymce.models import HTMLField
from django.core.urlresolvers import reverse
from PIL import Image

from functions.files import get_file_path
from commons.models import Country, Communications

class Category(models.Model):
    """ Форма вопроса с сайта для каждого раздела """

    name            = models.CharField(_(u'#Название'), max_length=255, help_text=_(u"Название раздела выводимое в меню"))
    url             = models.CharField(_(u'#Ссылка'), max_length=255, blank=True, null=True)
    sort            = models.IntegerField(_(u"#Порядок сортировки"), default=0, blank=True,)

    h1               = models.CharField(_(u'#Заголовок страницы H1'), max_length=255, blank=True, null=True)
    title           = models.CharField(_(u'#Заголовок'), max_length=255, blank=True, null=True)
    keywords        = models.CharField(_(u'#Ключевые'), max_length=255, blank=True, null=True)
    description     = models.CharField(_(u'#Описание'), max_length=255, blank=True, null=True)
    seo_text        = HTMLField(_(u'#СЕО-текст'), null=True, blank=True)

    show            = models.BooleanField(_(u'#Показывать'), default=True)
    created         = models.DateTimeField(_(u'#Дата создания'), auto_now_add=True,)

    def __unicode__(self):
        return u"%s" % self.name

    def get_absolute_url(self):
        return reverse('realty_category', args=[self.pk])

    class Meta:
        verbose_name = _(u'#Категории')
        verbose_name_plural = _(u'#Категории')
        ordering = ['sort',]


class Item(models.Model):
    """ Карточка товара (недвижимость) """

    SALE, RENT = range(0,2)
    TYPE_SALE = (
        (SALE, _(u'Продажа')),
        (RENT, _(u'Аренда')),
    )

    name            = models.CharField(_(u'#Название'), max_length=255, help_text=_(u"Название товара"))
    category        = models.ForeignKey(Category, verbose_name=_(u"Категория"), help_text=_(u"Раздел где выводится товар"), related_name="category")
    country         = models.ForeignKey(Country, verbose_name=_(u"Страна"), help_text=_(u"Страна товара"), related_name="item_category")
    price           = models.IntegerField(_(u"#Цена"), default=0,)
    type_sale       = models.IntegerField(_(u'#Тип продажи'), max_length=1, blank=True, default=SALE, choices=TYPE_SALE)
    hidden          = models.TextField(_(u'#Скрытое поле'), blank=True, null=True, help_text=_(u"Не выводится на сайт")) # ALTER TABLE `realty_item` ADD `hidden` LONGTEXT NOT NULL

    #itemchars       = models.ForeignKey('ItemChars', verbose_name=_(u"Характеристики товара"), blank=True, null=True, related_name="itemchars")
    #itemphoto       = models.ManyToManyField('ItemPhoto', verbose_name=_(u"Фотографии товара"), blank=True, null=True, related_name="itemphoto")

    show            = models.BooleanField(_(u'#Показывать'), default=True)
    created         = models.DateTimeField(_(u'#Дата создания'), auto_now_add=True,)

    def __setattr__(self, name, value):
        return super(Item, self).__setattr__(name, value)

    def get_absolute_url(self):
        return reverse('realty_item', args=[self.category_id, self.pk])

    def __unicode__(self):
        return u"%s: %s" % (self.name, self.pk)

    class Meta:
        verbose_name = _(u'#Товар')
        verbose_name_plural = _(u'#Товары')
        ordering = ['-pk',]

class ItemPhoto(models.Model):
    """ Фотографии товара """

    item            = models.ForeignKey(Item, verbose_name=_(u"Товар"), help_text=_(u"Связь с товаром"), blank=True, null=True, related_name="item_photo")
    big_image       = models.ImageField(_(u"большое изображение"), upload_to=get_file_path)
    main            = models.BooleanField(_(u'#Главная картинка'), default=False)

    def __unicode__(self):
        return self.pk

    def save(self, size_big=(500, 500), *args, **kwargs):
        # Ресайзим картинку
        super(ItemPhoto, self).save() #Вроде бы стоит супер вниз убрать, чтобы дважды не мучало файл
        # большую тоже сресайзим
        if self.big_image:
            filename = self.big_image.path
            image = Image.open(filename)
            image.thumbnail(size_big, Image.ANTIALIAS)
            image.save(filename, image.format)

    class Meta:
        verbose_name = u"#Изображение товара"
        verbose_name_plural = u"#Изображения товаров"
        #unique_together = (('item', 'show'))

class ItemChars(models.Model):
    """
    Характеристики товара
    """
    SECOND00, SECOND01, SECOND02 = range(0,3)
    CHAR04 = (
        (SECOND00, _(u"Строящееся")),
        (SECOND01, _(u"Новостройка")),
        (SECOND02, _(u"Вторичное")),
    )

    LOCAT00, LOCAT01, LOCAT02, LOCAT03 = range(0,4)
    CHAR06 = (
        (LOCAT00, _(u"Около моря")),
        (LOCAT01, _(u"Около гор")),
        (LOCAT02, _(u"В пустыне")),
        (LOCAT03, _(u"Лесная местность")),
    )

    NO, YES, PARTLY = range(0,3)
    CHAR07 = (
        (NO, _(u"Нет")),
        (YES, _(u"Да")),
        (PARTLY, _(u"Частично")),
    )
    CHAR10 = (
        (NO, _(u"Нет")),
        (YES, _(u"Да")),
    )
    CHAR13 = (
        (NO, _(u"Нет")),
        (YES, _(u"Да")),
    )
    CHAR14 = (
        (NO, _(u"Нет")),
        (YES, _(u"Да")),
    )

    REAL00, REAL01, REAL02, REAL03, REAL04, REAL05, REAL06, REAL07, REAL08 = range(0,9)
    CHAR16 = (
        (REAL00, _(u"Отель")),
        (REAL01, _(u"Ресторан")),
        (REAL02, _(u"Стоянка")),
        (REAL03, _(u"Офисные помещения")),
        (REAL04, _(u"Склады")),
        (REAL05, _(u"Курортные комплексы")),
        (REAL06, _(u"Магазины")),
        (REAL07, _(u"Доходные дома")),
        (REAL08, _(u"Студенческое жилье")),
    )

    item                       = models.ForeignKey(Item, verbose_name=_(u"Товар"), help_text=_(u"Связь с товаром"), blank=True, null=True, related_name="item_chars")
    chars01                    = models.CharField(_(u'#Количество комнат'), max_length=255, blank=True, null=True)
    chars02                    = models.CharField(_(u'#Общая площадь м2'), max_length=255, blank=True, null=True)
    chars12                    = models.CharField(_(u'#Жилая площадь м2'), max_length=255, blank=True, null=True) # ALTER TABLE `realty_itemchars` CHANGE `chars12` `chars12` VARCHAR( 255 ) NULL DEFAULT NULL
    chars03                    = models.CharField(_(u'#Количество сан узлов'), max_length=255, blank=True, null=True)
    chars04                    = models.IntegerField(_(u'#Тип'), max_length=1, blank=True, null=True, default=SECOND02, choices=CHAR04, help_text=_(u"Строящееся, новостройка, вторичное"))
    chars05                    = models.CharField(_(u'#Регион'), max_length=255, blank=True, null=True)
    chars06                    = models.IntegerField(_(u'#Расположение'), max_length=1, blank=True, null=True, default=LOCAT00, choices=CHAR06,)
    chars07                    = models.IntegerField(_(u'#Мебелирование'), max_length=1, blank=True, null=True, default=NO, choices=CHAR07,)
    chars08                    = models.IntegerField(_(u'#Всего этажей'), default=0, blank=True, null=True)
    chars09                    = models.IntegerField(_(u'#Этаж'), default=0, blank=True, null=True)
    chars10                    = models.IntegerField(_(u'#Балкон'), max_length=1, blank=True, null=True, default=NO, choices=CHAR10,)
    chars11                    = HTMLField(_(u'#Подробное описание'), blank=True, null=True)

    chars13                    = models.IntegerField(_(u'#Гараж'), max_length=1, blank=True, null=True, default=NO, choices=CHAR13,)
    chars14                    = models.IntegerField(_(u'#Легализация'), max_length=1, blank=True, null=True, default=NO, choices=CHAR14, help_text=_(u"Легализация под строительство"))
    chars15                    = models.ManyToManyField(Communications, verbose_name=_(u"Коммуникации"), null=True, blank=True)

    chars16                    = models.IntegerField(_(u'#Тип комерческой недвижимости'), max_length=255, blank=True, null=True, choices=CHAR16)
    chars17                    = models.IntegerField(_(u'#Рентабильность'), default=0, blank=True, null=True)



    def __unicode__(self):
        return u"Характеристики товара: %s" % self.pk

    class Meta:
        verbose_name = _(u'#Характеристика товара')
        verbose_name_plural = _(u'#Характеристики товара')

class OrdersForm(models.Model):
    """
    Форма заявок с сайта
    """
    item                    = models.ForeignKey(Item, verbose_name=_(u"Товар"), help_text=_(u"Связь с товаром"), blank=True, null=True, related_name="item_ordersform")
    fio                     = models.CharField(_(u'#ФИО'), max_length=255, blank=True, null=True)
    phone                   = models.CharField(_(u'#Телефон'), max_length=255, blank=True, null=True)
    email                   = models.EmailField(_(u'#Емайл'), max_length=255, blank=True, null=True)
    messages                = models.TextField(_(u'#Контакты в подвале сайта'), null=True, blank=True)
    created                 = models.DateTimeField(_(u'#Дата создания'), auto_now_add=True,)

    def __unicode__(self):
        return u"%s: %s" % (self.item.name, self.pk)

    class Meta:
        verbose_name = _(u'#Заявоки форма')
        verbose_name_plural = _(u'#Заявоки форма')
        ordering = ['-created',]

realty/forms.py
# -*- coding: utf-8 -*-
import re
from django.utils.translation import ugettext_lazy as _
from django import forms
from django.db.models import Q

from realty.models import OrdersForm

class OrdersFormForms(forms.ModelForm):
    """ Форма регистрации """

    def __init__(self, *args, **kwargs):
        super(OrdersFormForms, self).__init__(*args, **kwargs)


    def clean_fio(self):
        cleaned_data = self.cleaned_data.get('fio')

        if len(cleaned_data) < 3:
            raise forms.ValidationError(_(u'Минимум 3 символа'))
        return cleaned_data

    def clean_phone(self):
        cleaned_data = self.cleaned_data
        if cleaned_data:
            phones = re.sub(u"[^0-9+]*", "", cleaned_data.get('phone'))
            phones = re.sub(u"^8", "+7", phones)
            if len(phones) < 5:
                cleaned_data['phone'] = None
                raise forms.ValidationError(_(u'#Вы указали не верный формат телефона'))
            else:
                cleaned_data = phones
        return cleaned_data

    class Meta:
        model = OrdersForm

templates/realty/base_realty.html
{% extends "base.html" %}
{% load staticfiles i18n %}
{% block content %}
<div id="content_realty">

    <div class="realty_body">
    {% block content_realty %}
        sss
    {% endblock %}
    </div>
</div>
{% endblock %}

templates/realty/category.html
{% extends "realty/base_realty.html" %}
{% load staticfiles i18n thumbnail %}
{% block content_realty %}
    <div class="content_block">
        <h1>{% if seo %}{{ seo.h1 }}{% else %}{% trans 'Каталог зарубежной недвижимости' %}{% endif %}{% if type_page == 'country' %} - {{ category.name }}{% endif %}</h1>
        <div class="content_line"></div>
        {% if items %}
        {% for item in items %}
            <div class="items_list">
                <div id="items_left"><a href="{{ item.get_absolute_url }}">
                    {% if item.itemphoto %}{% thumbnail item.itemphoto.big_image "100x100" as im %}
                        <img src="{{ im.url }}">
                    {% endthumbnail %}
                    {% else %}
                        <img src="{% static 'img/no_img.jpg' %}">
                    {% endif %}

                </a></div>
                <div id="items_right">
                    <a href="{{ item.get_absolute_url }}"><h3>{{ item.name }}</h3></a>
                    <div class="number"> {% trans '№' %} {{ item.pk }}</div>
                    <div class="country" style="background-position: -{{ item.country.width }}px -{{ item.country.height }}px;"></div>{{ item.country }} <strong>{% if item.price == 0 %}{% trans 'По запросу' %}{% else %}{{ item.price }} {% trans 'euro' %}{% endif %}</strong><br>
                    {% if item.itemchars.chars02 %}{% trans 'Общая площадь' %}: {{ item.itemchars.chars02 }}м²<br>{% endif %}
                    {% if item.itemchars.chars12 %}{% trans 'Жилая площадь' %}: {{ item.itemchars.chars12 }}м²<br>{% endif %}
                    {% if item.itemchars.chars01 %}{% trans 'Количество комнат' %}: {{ item.itemchars.chars01 }}<br>{% endif %}
                    {% if item.itemchars.chars04 %}{% trans 'Тип' %}: {{ item.itemchars.get_chars04_display }}<br>{% endif %}
                    {% if item.itemchars.chars06 %}{% trans 'Расположение' %}: {{ item.itemchars.get_chars06_display }}<br>{% endif %}
                </div>
                <div class="clear"></div>
                </div>
        {% endfor %}
        <br>
        <div class="pagination">
        {# Вы спросите "это пагинатор?", даже луче, это БЫДЛОНАТОР 2000! #}
            <span class="step_links">
                {% if items.has_previous %}
                    <a href="{% if type_page == 'category' %}{% url "realty_category" category.pk items.previous_page_number %}{% else %}{% url "realty_country" category.pk items.previous_page_number %}{% endif %}" class="previous"></a>
                {% endif %}
                <span class="current">
                    {% for pag_num in pages_list %}
                        {% if page_id == pag_num %}<b>{{ pag_num }}</b>
                            {% else %}
                            {% if pag_num != "..." %}
                                <a href="{% if type_page == 'category' %}{% url "realty_category" category.pk pag_num  %}{% else %}{% url "realty_country" category.pk pag_num %}{% endif %}">{{ pag_num }}</a>
                            {% else %}<u class="tcheka">{{ pag_num }}</u>
                            {% endif %}
                        {% endif %}
                    {% endfor %}
                </span>
                {% if items.has_next %}
                    <a href="{% if type_page == 'category' %}{% url "realty_category" category.pk items.next_page_number %}{% else %}{% url "realty_country" category.pk items.next_page_number %}{% endif %}" class="next"></a>
                {% endif %}
            </span>
        </div>
        {% else %}
            {% trans 'Предложения отсутствуют' %}
        {% endif %}
        {% if seo %}
            <div class="clear"></div><div class="content_line"></div>
            {% autoescape off %}{{ seo.seo_text }}{% endautoescape %}
        {% endif %}
    </div>
{% endblock %}

templates/realty/index.html
{% extends "realty/base_realty.html" %}
{% load staticfiles i18n cms_tag thumbnail %}

{% block content_realty %}
    <div class="content_block">
        <h1>{% if seo %}{{ seo.h1 }}{% else %}{% trans 'Каталог зарубежной недвижимости' %}{% endif %}</h1>
        <div class="content_line"></div>
            {% if category %}
                <div class="left category_strong">{% trans 'Разделы' %}:</div>
                {% for categ in category %}
                    {% if categ.category.count %}<div class="category_menu"><a href="{{ categ.get_absolute_url }}">{{ categ.name }} ({{ categ.category.count }})</a></div>{% endif %}
                {% endfor %}
            {% else %}
                {% trans '#Категории не созданы' %}
            {% endif %}
            <div class="clear"></div>
             {% if country %}
                 <div class="left category_strong">{% trans 'Страны' %}:</div>
                {% for countr in country %}
                    {% if countr.item_category.count  %}<div class="category_menu"><a href="{% url 'realty_country' countr.pk %}">{{ countr.title }} ({{ countr.item_category.count }})</a></div>{% endif %}
                {% endfor %}
            {% else %}
                {% trans '#Страны не созданы' %}
            {% endif %}

        {% if items %}
            <div class="content_line"></div>
            {% for item in items %}
                <div class="items_list">
                    <div id="items_left"><a href="{{ item.get_absolute_url }}">
                        {% if item.itemphoto %}{% thumbnail item.itemphoto.big_image "100x100" as im %}
                            <img src="{{ im.url }}">
                        {% endthumbnail %}
                        {% else %}
                            <img src="{% static 'img/no_img.jpg' %}">
                        {% endif %}

                    </a></div>
                    <div id="items_right">
                        <a href="{{ item.get_absolute_url }}"><h3>{{ item.name }}</h3></a>
                        <div class="number"> {% trans '№' %} {{ item.pk }}</div>
                        <div class="country" style="background-position: -{{ item.country.width }}px -{{ item.country.height }}px;"></div>{{ item.country }} <strong>{% if item.price == 0 %}{% trans 'По запросу' %}{% else %}{{ item.price }} {% trans 'euro' %}{% endif %}</strong><br>
                        {% if item.itemchars.chars02 %}{% trans 'Общая площадь' %}: {{ item.itemchars.chars02 }}м²<br>{% endif %}
                        {% if item.itemchars.chars12 %}{% trans 'Жилая площадь' %}: {{ item.itemchars.chars12 }}м²<br>{% endif %}
                        {% if item.itemchars.chars01 %}{% trans 'Количество комнат' %}: {{ item.itemchars.chars01 }}<br>{% endif %}
                        {% if item.itemchars.chars04 %}{% trans 'Тип' %}: {{ item.itemchars.get_chars04_display }}<br>{% endif %}
                        {% if item.itemchars.chars06 %}{% trans 'Расположение' %}: {{ item.itemchars.get_chars06_display }}<br>{% endif %}
                    </div>
                    <div class="clear"></div>
                    </div>
            {% endfor %}
            <br>
            <div class="pagination">
            {# Вы спросите "это пагинатор?", даже луче, это БЫДЛОНАТОР 2000! #}
                <span class="step_links">
                    {% if items.has_previous %}
                        <a href="{% url "realty_index_page" items.previous_page_number %}" class="previous"></a>
                    {% endif %}
                    <span class="current">
                        {% for pag_num in pages_list %}
                            {% if page_id == pag_num %}<b>{{ pag_num }}</b>
                                {% else %}
                                {% if pag_num != "..." %}
                                    <a href="{% url "realty_index_page" pag_num %}">{{ pag_num }}</a>
                                {% else %}<u class="tcheka">{{ pag_num }}</u>
                                {% endif %}
                            {% endif %}
                        {% endfor %}
                    </span>
                    {% if items.has_next %}
                        <a href="{% url "realty_index_page" items.next_page_number %}" class="next"></a>
                    {% endif %}
                </span>
            </div>
        {% endif %}
        <div class="content_line"></div>
    {% section_text %}
    </div>
{% endblock %}

templates/realty/item.html
{% extends "realty/base_realty.html" %}
{% load staticfiles i18n thumbnail %}
{% block content_realty %}
    <div class="content_block">
        <h1>{{ item.name }}</h1>
        <div class="content_line"></div>
        <div id="item">
            <div class="img">
                {% if item.itemphoto.all %}
                    {% for photo in item.itemphoto.all %}
                    {% if forloop.first %}
                        <a href="{{ MEDIA_URL }}{{ photo.big_image }}" title="{{ photo.big_image }}" rel="lightbox">
                            <img id="main_photo" src="{{ MEDIA_URL }}{{ photo.big_image }}">
                        </a><div class="clear"></div>
                    {% else %}
                        <a href="{{ MEDIA_URL }}{{ photo.big_image }}" title="{{ photo.big_image }}" rel="lightbox">
                            {% thumbnail photo.big_image "x50" as im %}<img src="{{ im.url }}">{% endthumbnail %}
{#                            <img src="{{ MEDIA_URL }}{{ photo.big_image }}">#}
                        </a>
                    {% endif %}
                    {% endfor %}
                {% else %}
                    <img src="{% static 'img/no_img2.jpg' %}">
                {% endif %}
            </div>
            <div class="item_bottom">
                <div class="item_price">{% trans 'Стоимость' %}: {% if item.price == 0 %}<b>{% trans 'По запросу' %}</b>{% else %}<b>{{ item.price }}</b> {% trans 'euro' %}{% endif %}</div>
                <div class="country" style="background-position: -{{ item.country.width }}px -{{ item.country.height }}px;"></div>{{ item.country }}<br>
                <a href="#" class="buy_realrty">{% trans 'Отправить заявку' %}</a>
{#                <a href="">{% trans 'Заказать обратный звонок' %}</a>#}
                <div id="item_modal" rel="{{ item.pk }}">
                    <a href="#" class="closed">{% trans 'Закрыть' %}</a>
                    <div class="form_messages"></div>
                    <form method="post" class="realty_form">
                        {% csrf_token %}
                        <input type="hidden" name="item" value="{{ item.pk }}">
                        {% trans 'Ваше имя' %}<br><input type="text" name="fio" required><br>
                        {% trans 'Ваш телефон' %}<br><input type="text" name="phone" required><br>
                        {% trans 'Ваш email' %}<br><input type="text" name="email"><br>
                        {% trans 'Комментарий' %}<br><textarea name="messages"></textarea><br>
                        <input type="submit" value="отправить">

                    </form>
                </div>
            </div>
            <div class="info">
                <strong>{% trans 'Харрактеристики недвижимости' %}</strong>
                {% if item.itemchars %}<ul>
                    {% if item.itemchars.chars01 %}<li>{% trans 'Количество комнат' %}: {{ item.itemchars.chars01 }}</li>{% endif %}
                    {% if item.itemchars.chars02 %}<li>{% trans 'Общая площадь' %}: {{ item.itemchars.chars02 }}м²</li>{% endif %}
                    {% if item.itemchars.chars03 %}<li>{% trans 'Количество сан узлов' %}: {{ item.itemchars.chars03 }}</li>{% endif %}
                    {% if item.itemchars.chars04 %}<li>{% trans 'Тип' %}: {{ item.itemchars.get_chars04_display }}</li>{% endif %}
                    {% if item.itemchars.chars05 %}<li>{% trans 'Регион' %}: {{ item.itemchars.chars05 }}</li>{% endif %}
                    {% if item.itemchars.chars06 %}<li>{% trans 'Расположение' %}: {{ item.itemchars.get_chars06_display }}</li>{% endif %}
                    {% if item.itemchars.chars07 %}<li>{% trans 'Мебелирование' %}: {{ item.itemchars.get_chars07_display }}</li>{% endif %}
                    {% if item.itemchars.chars08 %}<li>{% trans 'Всего этажей' %}: {{ item.itemchars.chars08 }}</li>{% endif %}
                    {% if item.itemchars.chars09 %}<li>{% trans 'Этаж' %}: {{ item.itemchars.chars09 }}</li>{% endif %}
                    {% if item.itemchars.chars10 %}<li>{% trans 'Балкон' %}: {{ item.itemchars.get_chars10_display }}</li>{% endif %}
                    {% if item.itemchars.chars12 %}<li>{% trans 'Жилая площадь' %}: {{ item.itemchars.chars12 }}м²</li>{% endif %}
                    {% if item.itemchars.chars13 %}<li>{% trans 'Гараж' %}: {{ item.itemchars.get_chars13_display }}</li>{% endif %}
                    {% if item.itemchars.chars14 %}<li>{% trans 'Легализация' %}: {{ item.itemchars.get_chars14_display }}</li>{% endif %}
                    {% if item.itemchars.chars15 and item.itemchars.chars15.all %}<li>{% trans 'Коммуникации' %}: {% for chars15 in item.itemchars.chars15.all %}{{ chars15.name }}{% if not forloop.last %}, {% endif %}{% endfor %}</li>{% endif %}
                    {% if item.itemchars.chars16 %}<li>{% trans 'Тип комерческой недвижимости' %}: {{ item.itemchars.get_chars16_display }}</li>{% endif %}
                    {% if item.itemchars.chars17 %}<li>{% trans 'Рентабильность' %}: {{ item.itemchars.chars17 }} %</li>{% endif %}
                </ul>{% endif %}
            </div>
            <div class="clear"></div><div class="content_line"></div>
            {% if item.itemchars.chars11 %}<div class="big_info">
                <strong>{% trans 'Описание недвижимости' %}</strong><br>
                {% autoescape off %}{{ item.itemchars.chars11 }}{% endautoescape %}
            </div>{% endif %}
        </div>

    </div>
{% endblock %}

{% block extended_css %}
    <link href="/static/lightbox/css/lightbox.css" rel="stylesheet" />
{% endblock %}

{% block extended_js %}
    <script type="text/javascript" src="/static/lightbox/js/lightbox.js"></script>
{% endblock %}